src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: " Nom doit etre non vide")]
    #[Assert\Length(min : 4,minMessage:" Entrer un nom au mini de 4 caractères")]
    #[ORM\Column(length: 255)]
    private ?string $nom_evn = null;

    #[Assert\NotBlank(message: " Libelle doit etre non vide")]
    #[Assert\Length(min : 3,minMessage:" Entrer un libelle au mini de 3 caractères")]
    #[ORM\Column(length: 255)]
    private ?string $libelle_evn = null;

    #[Assert\NotBlank(message: " Type doit etre non vide")]
    #[Assert\Length(min : 4,minMessage:" Entrer un type au mini de 4 caractères")]
    #[ORM\Column(length: 255)]
    private ?string $type_evn = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_evn = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Location $location = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEvn(): ?string
    {
        return $this->nom_evn;
    }

    public function setNomEvn(string $nom_evn): self
    {
        $this->nom_evn = $nom_evn;

        return $this;
    }

    public function getLibelleEvn(): ?string
    {
        return $this->libelle_evn;
    }

    public function setLibelleEvn(string $libelle_evn): self
    {
        $this->libelle_evn = $libelle_evn;

        return $this;
    }

    public function getTypeEvn(): ?string
    {
        return $this->type_evn;
    }

    public function setTypeEvn(string $type_evn): self
    {
        $this->type_evn = $type_evn;

        return $this;
    }

    public function getDateEvn(): ?\DateTimeInterface
    {
        return $this->date_evn;
    }

    public function setDateEvn(\DateTimeInterface $date_evn): self
    {
        $this->date_evn = $date_evn;

        return $this;
    }

    public function getLocation(): ?location
    {
        return $this->location;
    }

    public function setLocation(?location $location): self
    {
        $this->location = $location;

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_evn')
            ->add('libelle_evn')
            ->add('type_evn')
            ->add('date_evn')
            ->add('location')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/evenement')]
class EvenementController extends AbstractController
{
    #[Route('/', name: 'app_evenement_index', methods: ['GET'])]
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_evenement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EvenementRepository $evenementRepository): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $evenementRepository->save($evenement, true);

            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evenement_show', methods: ['GET'])]
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_evenement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Evenement $evenement, EvenementRepository $evenementRepository): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $evenementRepository->save($evenement, true);

            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evenement_delete', methods: ['POST'])]
    public function delete(Request $request, Evenement $evenement, EvenementRepository $evenementRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $evenementRepository->remove($evenement, true);
        }

        return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('app_evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/evenement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}

templates/evenement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement index{% endblock %}

{% block body %}
    <h1>Evenement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_evn</th>
                <th>Libelle_evn</th>
                <th>Type_evn</th>
                <th>Date_evn</th>
                <th>Location</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.nomEvn }}</td>
                <td>{{ evenement.libelleEvn }}</td>
                <td>{{ evenement.typeEvn }}</td>
                <td>{{ evenement.dateEvn ? evenement.dateEvn|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.location }}</td>
                <td>
                    <a href="{{ path('app_evenement_show', {'id': evenement.id}) }}">show</a>
                    <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_evenement_new') }}">Create new</a>
{% endblock %}

templates/evenement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Evenement{% endblock %}

{% block body %}
    <h1>Create new Evenement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('app_evenement_index') }}">back to list</a>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <h1>Evenement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ evenement.id }}</td>
            </tr>
            <tr>
                <th>Nom_evn</th>
                <td>{{ evenement.nomEvn }}</td>
            </tr>
            <tr>
                <th>Libelle_evn</th>
                <td>{{ evenement.libelleEvn }}</td>
            </tr>
            <tr>
                <th>Type_evn</th>
                <td>{{ evenement.typeEvn }}</td>
            </tr>
            <tr>
                <th>Date_evn</th>
                <td>{{ evenement.dateEvn ? evenement.dateEvn|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ evenement.location}}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_evenement_index') }}">back to list</a>

    <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}">edit</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}