src/Entity/Salle.php
<?php

namespace App\Entity;

use App\Repository\SalleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\DispoConstraint as validation;


#[ORM\Entity(repositoryClass: SalleRepository::class)]
class Salle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: " Numéro doit etre non vide")]
    #[ORM\Column]
    #[Assert\Positive]
    private ?int $num_salle = null;

    
    #[ORM\Column]
    #[Assert\Valid]
    #[Assert\Choice(choices: [0, 1])]
    private ?int $dispo = null;

    #[ORM\ManyToOne(inversedBy: 'salle')]
    private ?Location $location = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumSalle(): ?int
    {
        return $this->num_salle;
    }

    public function setNumSalle(int $num_salle): self
    {
        $this->num_salle = $num_salle;

        return $this;
    }

    public function getDispo(): ?int
    {
        return $this->dispo;
    }

    public function setDispo(int $dispo): self
    {
        $this->dispo = $dispo;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }
}

src/Form/SalleType.php
<?php

namespace App\Form;

use App\Entity\Salle;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SalleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('num_salle')
            ->add('dispo')
            ->add('location')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Salle::class,
        ]);
    }
}

src/Controller/SalleController.php
<?php

namespace App\Controller;

use App\Entity\Salle;
use App\Form\SalleType;
use App\Repository\SalleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/salle')]
class SalleController extends AbstractController
{
    #[Route('/', name: 'app_salle_index', methods: ['GET'])]
    public function index(SalleRepository $salleRepository): Response
    {
        return $this->render('salle/index.html.twig', [
            'salles' => $salleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_salle_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SalleRepository $salleRepository): Response
    {
        $salle = new Salle();
        $form = $this->createForm(SalleType::class, $salle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $salleRepository->save($salle, true);

            return $this->redirectToRoute('app_salle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('salle/new.html.twig', [
            'salle' => $salle,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_salle_show', methods: ['GET'])]
    public function show(Salle $salle): Response
    {
        return $this->render('salle/show.html.twig', [
            'salle' => $salle,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_salle_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Salle $salle, SalleRepository $salleRepository): Response
    {
        $form = $this->createForm(SalleType::class, $salle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $salleRepository->save($salle, true);

            return $this->redirectToRoute('app_salle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('salle/edit.html.twig', [
            'salle' => $salle,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_salle_delete', methods: ['POST'])]
    public function delete(Request $request, Salle $salle, SalleRepository $salleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$salle->getId(), $request->request->get('_token'))) {
            $salleRepository->remove($salle, true);
        }

        return $this->redirectToRoute('app_salle_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/salle/_delete_form.html.twig
<form method="post" action="{{ path('app_salle_delete', {'id': salle.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ salle.id) }}">
    <button class="btn">Delete</button>
</form>

templates/salle/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/salle/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Salle{% endblock %}

{% block body %}
    <h1>Edit Salle</h1>

    {{ include('salle/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_salle_index') }}">back to list</a>

    {{ include('salle/_delete_form.html.twig') }}
{% endblock %}

templates/salle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salle index{% endblock %}

{% block body %}
    <h1>Salle index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Num_salle</th>
                <th>Dispo</th>
                <th>Location</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for salle in salles %}
            <tr>
                <td>{{ salle.id }}</td>
                <td>{{ salle.numSalle }}</td>
                <td>{{ salle.dispo }}</td>
                <td>{{ salle.location }}</td>
                <td>
                    <a href="{{ path('app_salle_show', {'id': salle.id}) }}">show</a>
                    <a href="{{ path('app_salle_edit', {'id': salle.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_salle_new') }}">Create new</a>
{% endblock %}

templates/salle/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Salle{% endblock %}

{% block body %}
    <h1>Create new Salle</h1>

    {{ include('salle/_form.html.twig') }}

    <a href="{{ path('app_salle_index') }}">back to list</a>
{% endblock %}

templates/salle/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salle{% endblock %}

{% block body %}
    <h1>Salle</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ salle.id }}</td>
            </tr>
            <tr>
                <th>Num_salle</th>
                <td>{{ salle.numSalle }}</td>
            </tr>
            <tr>
                <th>Dispo</th>
                <td>{{ salle.dispo }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ salle.location }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_salle_index') }}">back to list</a>

    <a href="{{ path('app_salle_edit', {'id': salle.id}) }}">edit</a>

    {{ include('salle/_delete_form.html.twig') }}
{% endblock %}